ALTER TABLE Employee ADD COLUMN username   character varying (10);
ALTER TABLE Employee ADD COLUMN passwrd   character varying (20);
UPDATE Employee SET username='ADA1' WHERE EmployeeId =1;
UPDATE Employee SET passwrd='pijama' WHERE EmployeeId =1;
UPDATE Employee SET username='EDW2' WHERE EmployeeId =2;
UPDATE Employee SET passwrd='cuaderno' WHERE EmployeeId =2;
UPDATE Employee SET username='PEA3' WHERE EmployeeId =3;
UPDATE Employee SET passwrd='agua de coco' WHERE EmployeeId =3;
UPDATE Employee SET username='PAR4' WHERE EmployeeId =4;
UPDATE Employee SET passwrd='lapiz' WHERE EmployeeId =4;
UPDATE Employee SET username='JOH5' WHERE EmployeeId =5;
UPDATE Employee SET passwrd='kitty' WHERE EmployeeId =5;
UPDATE Employee SET username='MIT6' WHERE EmployeeId =6;
UPDATE Employee SET passwrd='verde' WHERE EmployeeId =6;
UPDATE Employee SET username='KIN7' WHERE EmployeeId =7;
UPDATE Employee SET passwrd='rey' WHERE EmployeeId =7;
UPDATE Employee SET username='CAL8' WHERE EmployeeId =8;
UPDATE Employee SET passwrd='revista' WHERE EmployeeId =8;